# Generated by Django 5.0.1 on 2025-12-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClusteringResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('n_clusters', models.IntegerField()),
                ('algorithm', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobClusterPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_title', models.CharField(max_length=200)),
                ('salary_usd', models.FloatField()),
                ('experience_level', models.CharField(max_length=50)),
                ('employment_type', models.CharField(max_length=50)),
                ('company_location', models.CharField(max_length=100)),
                ('company_size', models.CharField(max_length=50)),
                ('years_experience', models.FloatField()),
                ('predicted_cluster', models.IntegerField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.FloatField()),
                ('years_of_experience', models.FloatField()),
                ('gender', models.CharField(max_length=50)),
                ('education_level', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=200)),
                ('predicted_salary', models.FloatField()),
                ('model_used', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
