# Generated by Django 5.0.1 on 2025-12-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_title_simplified', models.CharField(max_length=200)),
                ('job_country', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('job_work_from_home', models.BooleanField()),
                ('job_no_degree_mention', models.BooleanField()),
                ('job_health_insurance', models.BooleanField()),
                ('predicted_platform', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('model_used', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
