# Generated by Django 6.0 on 2025-12-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0002_platformprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitlePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_schedule_type', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=200)),
                ('job_via', models.CharField(max_length=100)),
                ('job_skills', models.IntegerField()),
                ('predicted_job_title', models.CharField(max_length=200)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('model_used', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
