# Generated by Django 6.0 on 2025-12-22 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0005_timeseriesprediction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeClusterPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salary_usd', models.FloatField()),
                ('benefits_score', models.FloatField()),
                ('years_experience', models.FloatField()),
                ('remote_ratio', models.FloatField()),
                ('predicted_cluster', models.CharField(max_length=50)),
                ('kmeans_cluster', models.IntegerField(blank=True, null=True)),
                ('agglomerative_cluster', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperiencePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('industry', models.CharField(max_length=200)),
                ('education_required', models.CharField(max_length=100)),
                ('required_skills', models.CharField(max_length=500)),
                ('employment_type', models.CharField(max_length=50)),
                ('experience_level', models.CharField(max_length=50)),
                ('company_size', models.CharField(max_length=50)),
                ('predicted_years', models.FloatField()),
                ('model_used', models.CharField(max_length=100)),
                ('all_predictions', models.JSONField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
