# Generated by Django 6.0 on 2025-12-22 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0006_employeeclusterprediction_experienceprediction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySegmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sector_group', models.CharField(max_length=200)),
                ('company_size', models.CharField(max_length=50)),
                ('ai_profile', models.CharField(max_length=50)),
                ('predicted_cluster', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAnalysisPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('year_experience', models.FloatField()),
                ('nb_skills', models.IntegerField()),
                ('job_description_length', models.IntegerField()),
                ('benefits_score', models.FloatField()),
                ('company_size', models.CharField(max_length=50)),
                ('seniority', models.CharField(max_length=50)),
                ('ai_profile', models.CharField(max_length=50)),
                ('sector_group', models.CharField(max_length=200)),
                ('company_location', models.CharField(max_length=100)),
                ('predicted_salary_usd', models.FloatField(blank=True, null=True)),
                ('salary_model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('predicted_ai_profile', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_profile_confidence', models.FloatField(blank=True, null=True)),
                ('prediction_type', models.CharField(max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
